<div class="row">
    <div class="col-md-6">
        <p>{{ flashSession.output() }}</p> 
       
        {% if motorbikes.items %}
            <table class="table">
                <tr>
                    <th>#</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr> 
                {% set i = 0, token = security.getToken() %} 
                {% for motorbike in motorbikes.items %}
                    {% set i += 1 %}
                    <tr>
                        <td>{{i}}</td>
                        <td>{{motorbike.id}}</td>
                        <td>{{motorbike.name}}</td>
                        <td>
                            <a href="{{ url("admin/index/delete/" ~ motorbike.id) ~ "?token=" ~ token }}" >Delete</a>
                            <a href="{{ url("admin/index/edit/" ~ motorbike.id) }}" >Edit</a>
                        </td>
                    </tr>
                {% endfor %} 
            </table>
        {% endif %}
        <a href="{{ url("admin/index/index") }}">First</a>
        <a href="{{ url("admin/index/index") }}?page={{ motorbikes.before }}">Previous</a>
        <a href="{{ url("admin/index/index") }}?page={{ motorbikes.next }}">Next</a>
        <a href="{{ url("admin/index/index") }}?page={{ motorbikes.last }}">Last</a>
       
        You are in page {{ motorbikes.current }} of {{ motorbikes.total_pages }} - total items :  {{ motorbikes.total_items }}
    </div>
    <div class="col-md-6">
        {{link_to(url("admin/index/add"), 'Add New Record')}}
    </div>
</div>