<div class="row">
    <div class="col-md-6">
        <p>{{ flashSession.output() }}</p>
        {% if motorbikes %}
            <table class="table">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>  
                {% for motorbike in motorbikes %}
                    <tr>
                        <td>{{motorbike.id}}</td>
                        <td>{{motorbike.name}}</td>
                    </tr>
                {% endfor %} 
            </table>
        {% endif %}
    </div>
    <div class="col-md-6">
        {{link_to('/admin/index/add', 'Add New Record')}}
    </div>
</div>